name: GitHub Pages - Python Sphinx

on:
  push:
    branches:
      - main

jobs:
  docs:
    uses: darbiadev/.github/.github/workflows/github-pages-python-sphinx.yaml@0c105e4ec7fd13ac581ccd1ea3fe5f25091ddc14
